### ISSUE TITLE
AttributeError: module 're' has no attribute 'Pattern' 

### ISSUE THREAD

**Issue by TCP-88** [pysonDB/pysonDB#75]
Hi , im having this error when i try to import the db. so sorry im new here.

i have intalled this version:
pysondb                1.5.6

(test_project_env) [root@test-01 test_testing-json.py]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysondb import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/ftp_project_env/lib64/python3.6/site-packages/pysondb/db.py", line 74, in <module>
    class JsonDatabase:
  File "/data/ftp_project_env/lib64/python3.6/site-packages/pysondb/db.py", line 234, in JsonDatabase
    self, key: str, _re: Union[str, re.Pattern]
AttributeError: module 're' has no attribute 'Pattern'
>>>

**Comment by Adwaith-Rajesh** [comment]
Do you have a file named `re.py` in the same dir by any chance?

**Comment by TCP-88** [comment]
> Do you have a file named `re.py` in the same dir by any chance?

Hi Thanks for reply, i try to create new dir and create new venv also having this issue. im running (CentOS Linux release 7.9.2009 (Core), when i run on windwos 10 no issue.

**Comment by Adwaith-Rajesh** [comment]
It works on, ubuntu too. But as far I've seen, this might be due to a broken python installation.

https://www.reddit.com/r/inventwithpython/comments/exypps/chapter_8_error_module_re_has_no_attribute_pattern/

**Comment by TCP-88** [comment]
> It works on, ubuntu too. But as far I've seen, this might be due to a broken python installation.
> 
> https://www.reddit.com/r/inventwithpython/comments/exypps/chapter_8_error_module_re_has_no_attribute_pattern/

Hi, Thanks. problem resolved by reinstalling python3.6 in centos

**Comment by aneeshbhadran** [comment]
@TCP-88 , May I know what is the exact version of python which you installed. I am getting the same error on Python 3.6.13 also in Python 3.6.8 too. But not in the 3.8 version.  All the environments has been created in Ananconda

**Comment by Adwaith-Rajesh** [comment]
@aneeshbhadran he was using 3.6.8

**Comment by Adwaith-Rajesh** [comment]
Its also not working on 3.6.14

**Comment by Adwaith-Rajesh** [comment]
@aneeshbhadran  I just released a new update, can you pls verify it.

```commandline
Python 3.6.14 (default, Jul 30 2021, 12:25:22) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysondb import db
>>> a = db.getDb("test.json")
>>> a.add({"name": "test"})
333231764069881129
>>> 


````

**Comment by Adwaith-Rajesh** [comment]
The latest version of PythonDB is `v.1.5.7`

**Comment by aneeshbhadran** [comment]
Thank you @Adwaith-Rajesh. It is working now.

**Comment by fredysomy** [comment]
Closing this issue.
